name: mayfair
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.20.5+24

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl:
  http:
  dio:
  get:
  get_storage:
  google_fonts:
  flutter_screenutil:
  table_calendar:
  flutter_spinkit:
  image_picker:
  connectivity_plus:
  http_parser:
  firebase_database:
  firebase_auth:
  firebase_core:
  firebase_messaging:
  flutter_local_notifications: ^13.0.0
  image_cacheing:
  icons_launcher:
  shared_preferences: ^2.0.15
  cached_network_image: ^3.0.0
  package_info_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: 'assets/app_icon.png'
  ios: true
  android: true

  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/icons/
    - assets/png/
    - assets/app_icon.png
